#put any key/value pairs here
skamidmap.macro.desc = A map of the dishes at SKA-Mid.
skamiddishbookings.macro.desc = A calendar view of bookings for each dish.
skamiddishbookings.macro.param.calendar.desc= Start typing for calendar suggestions. 